services:  # FastAPI Python Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lma-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000
    networks:
      - lma-network
  # SvelteKit Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lma-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - lma-network
volumes: {}

networks:
  lma-network:
    driver: bridge
