services:
  # FastAPI Python Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lma-backend
    ports:
      - "18000:8000"
    environment:
      - ENVIRONMENT=development
      - PORT=8000
      - DATABASE_URL=postgresql://lma_db_owner:npg_mRQX3eAio4tL@ep-old-butterfly-a6ids19o-pooler.us-west-2.aws.neon.tech/lma_db?sslmode=require
    networks:
      - lma-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # SvelteKit Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lma-frontend
    ports:
      - "15173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - PUBLIC_API_URL=http://localhost:18000/api
      - DATABASE_URL=postgresql://lma_db_owner:npg_mRQX3eAio4tL@ep-old-butterfly-a6ids19o-pooler.us-west-2.aws.neon.tech/lma_db?sslmode=require
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - /app/node_modules
    depends_on:
      - backend
      # - postgres
    networks:
      - lma-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  lma-network:
    driver: bridge
