global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@lma.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/alerts'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/alerts'
    send_resolved: true

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/alerts'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 