groups:
  - name: automation_alerts
    rules:
      # High Error Rate Alerts
      - alert: AutomationHighErrorRate
        expr: |
          (
            rate(automation_execution_errors_total[5m]) / 
            rate(automation_executions_total[5m])
          ) > 0.1
        for: 2m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "High error rate in automation executions"
          description: "Automation script {{ $labels.script_name }} has an error rate of {{ $value | humanizePercentage }} over the last 5 minutes."

      - alert: AutomationCriticalErrorRate
        expr: |
          (
            rate(automation_execution_errors_total[5m]) / 
            rate(automation_executions_total[5m])
          ) > 0.25
        for: 1m
        labels:
          severity: critical
          component: automation
        annotations:
          summary: "Critical error rate in automation executions"
          description: "Automation script {{ $labels.script_name }} has a critical error rate of {{ $value | humanizePercentage }} over the last 5 minutes."

      # Execution Performance Alerts
      - alert: AutomationSlowExecution
        expr: |
          histogram_quantile(0.95, rate(automation_execution_duration_seconds_bucket[5m])) > 30
        for: 3m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "Slow automation script execution"
          description: "95th percentile execution time for {{ $labels.script_name }} is {{ $value }}s, which is above the 30s threshold."

      - alert: AutomationVerySlowExecution
        expr: |
          histogram_quantile(0.95, rate(automation_execution_duration_seconds_bucket[5m])) > 60
        for: 1m
        labels:
          severity: critical
          component: automation
        annotations:
          summary: "Very slow automation script execution"
          description: "95th percentile execution time for {{ $labels.script_name }} is {{ $value }}s, which is above the critical 60s threshold."

      # Stuck Executions
      - alert: AutomationStuckExecutions
        expr: |
          automation_active_executions > 0 and 
          increase(automation_active_executions[10m]) == 0
        for: 5m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "Automation executions appear to be stuck"
          description: "Script {{ $labels.script_name }} has {{ $value }} active executions that haven't changed in 10 minutes."

      # System Health Alerts
      - alert: AutomationSystemUnhealthy
        expr: automation_system_health == 0
        for: 1m
        labels:
          severity: critical
          component: automation
        annotations:
          summary: "Automation system component unhealthy"
          description: "Automation component {{ $labels.component }} is reporting unhealthy status."

      # Webhook Alerts
      - alert: WebhookHighErrorRate
        expr: |
          (
            rate(webhook_processing_errors_total[5m]) / 
            rate(webhook_events_received_total[5m])
          ) > 0.1
        for: 2m
        labels:
          severity: warning
          component: webhook
        annotations:
          summary: "High error rate in webhook processing"
          description: "Webhook event type {{ $labels.event_type }} has an error rate of {{ $value | humanizePercentage }} over the last 5 minutes."

      - alert: WebhookProcessingSlow
        expr: |
          histogram_quantile(0.95, rate(webhook_processing_duration_seconds_bucket[5m])) > 10
        for: 2m
        labels:
          severity: warning
          component: webhook
        annotations:
          summary: "Slow webhook processing"
          description: "95th percentile webhook processing time for {{ $labels.event_type }} is {{ $value }}s, which is above the 10s threshold."

      # Scheduler Alerts
      - alert: ScheduledJobFailures
        expr: |
          rate(automation_job_executions_total{status="failed"}[10m]) > 0
        for: 1m
        labels:
          severity: warning
          component: scheduler
        annotations:
          summary: "Scheduled job failures detected"
          description: "Scheduled job {{ $labels.job_id }} (script: {{ $labels.script_name }}) is failing."

      # Database Connection Alerts
      - alert: AutomationHighDbConnections
        expr: automation_db_connections_active > 20
        for: 2m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "High number of database connections from automation"
          description: "Automation system is using {{ $value }} database connections, which is above the 20 connection threshold."

      # Queue Size Alerts
      - alert: AutomationQueueBacklog
        expr: automation_queue_size > 100
        for: 5m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "Automation queue has backlog"
          description: "Queue {{ $labels.queue_type }} has {{ $value }} items, indicating a potential backlog."

      # Last Execution Alerts
      - alert: AutomationScriptNotExecuted
        expr: |
          time() - automation_last_execution_timestamp > 3600
        for: 0m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "Automation script hasn't executed recently"
          description: "Script {{ $labels.script_name }} hasn't executed successfully in over 1 hour."

      # Memory and Resource Alerts
      - alert: AutomationHighMemoryUsage
        expr: automation_memory_usage_bytes > 500000000  # 500MB
        for: 5m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "High memory usage in automation component"
          description: "Component {{ $labels.component }} is using {{ $value }} bytes of memory (threshold: 500MB)."

      - alert: AutomationHighCpuUsage
        expr: automation_cpu_usage_percent > 80
        for: 3m
        labels:
          severity: warning
          component: automation
        annotations:
          summary: "High CPU usage in automation component"
          description: "Component {{ $labels.component }} is using {{ $value }}% CPU."

  - name: automation_capacity
    rules:
      # Capacity Planning Rules
      - alert: AutomationHighThroughput
        expr: |
          rate(automation_executions_total[5m]) > 10
        for: 5m
        labels:
          severity: info
          component: automation
        annotations:
          summary: "High automation throughput"
          description: "Automation system is processing {{ $value }} executions per second, consider scaling if sustained."

      - alert: WebhookHighThroughput
        expr: |
          rate(webhook_events_received_total[5m]) > 50
        for: 5m
        labels:
          severity: info
          component: webhook
        annotations:
          summary: "High webhook throughput"
          description: "Webhook system is receiving {{ $value }} events per second, consider scaling if sustained."

  - name: automation_business_logic
    rules:
      # Business Logic Alerts
      - alert: LeadScoringScriptFailures
        expr: |
          rate(automation_execution_errors_total{script_name="lead_scoring"}[10m]) > 0
        for: 1m
        labels:
          severity: critical
          component: automation
          business_impact: high
        annotations:
          summary: "Lead scoring automation failing"
          description: "The lead scoring script is failing, which impacts lead qualification process."

      - alert: WebhookLeadCreationFailures
        expr: |
          rate(webhook_processing_errors_total{event_type="lead_created"}[10m]) > 0
        for: 1m
        labels:
          severity: critical
          component: webhook
          business_impact: high
        annotations:
          summary: "Lead creation webhook processing failing"
          description: "Webhook processing for lead creation events is failing, impacting lead ingestion."

      - alert: EmailAutomationFailures
        expr: |
          rate(automation_execution_errors_total{script_name="send_welcome_email"}[10m]) > 0
        for: 2m
        labels:
          severity: warning
          component: automation
          business_impact: medium
        annotations:
          summary: "Email automation failing"
          description: "Welcome email automation is failing, affecting user onboarding experience." 