apiVersion: v1
kind: PersistentVolume
metadata:
  name: lma-pv
  namespace: lma
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/lma-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lma-pvc
  namespace: lma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
